// layout.js
import "./globals.css";
import Sidebar from "./Components/Sidebar";
import RightSideBar from "./Components/RightSideBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Sidebar />
        <div className="ml-80">
          {children}
        </div>
        <RightSideBar />
      </body>
    </html>
  );
}
